### ISSUE TITLE
Archive the repository

### ISSUE THREAD

**Issue by JL2210** [nrnrnr/qc--#1]
As this repository is no longer maintained, could you archive it? The setting to archive is located at the bottom of the repository settings page.

**Comment by nrnrnr** [comment]
Please educate me on the pros and cons of archiving a repository.

**Comment by JL2210** [comment]
@nrnrnr No issues can be opened, no pull requests can be opened, etc. Basically, no changes can be made after archiving (hence the term "archive"). This makes it clear that the project is no longer maintained. If need arises, the repository can be un-archived in the same place where it was archived.

**Comment by nrnrnr** [comment]
OK, seems like it does no harm...
